---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudfare

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudfare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared
        command: ["cloudflared", "tunnel", "--no-autoupdate", "run"]
        envFrom:
        - configMapRef:
            name: cloudflared-env
